name: reconstruction-mass
num_layers: 8
num_heads: 8
dim_embedding: 512
batch_size_per_device: 128
learning_rate: 0.00002
max_epochs: 10
observation_variance: 0.0
prediction_target: mass
pretrained_ckpt_dir: ntp-pretrain
pretrained_output_dim: 2
store_predictions: True
prediction_path: reconstruction_mass_predictions
use_wandb: True
wandb_project: iclr-reconstruction-mass-fixed
wandb_entity: petergchang
