name: sp_pretrained_fsp_transfer
num_layers: 8
num_heads: 8
dim_embedding: 512
batch_size_per_device: 128
learning_rate: 0.00002
max_epochs: 10
observation_variance: 0.0
prediction_target: function_of_state
pretrained_ckpt_dir: fig2-sp-pretrain
pretrained_output_dim: 8
use_wandb: True
wandb_project: iclr-transfer-learning-latest
wandb_entity: petergchang
