name: sp-pretrain-1mil-deep
num_layers: 12
num_heads: 16
dim_embedding: 512
batch_size_per_device: 128
learning_rate: 0.00005
max_epochs: 50
observation_variance: 0.0
prediction_target: state
use_wandb: True
wandb_project: iclr-sp-pretrain-1mil
wandb_entity: petergchang
