name: sp_pt_noise_finetune3-1mil
num_layers: 12
num_heads: 16
dim_embedding: 512
batch_size_per_device: 128
learning_rate: 0.00002
max_epochs: 100
observation_variance: 0.0
prediction_target: noise
pretrained_ckpt_dir: sp-pretrain-1mil-deep
pretrained_output_dim: 10
use_wandb: True
wandb_project: iclr-noise-prediction-1mil
wandb_entity: petergchang
seed: 3
